import json from '../staff/data.json'
import Head from 'next/head';
import styles from '../styles/Home.module.css';


const data = json.data;
// console.log(data[0])

const Card = () => {
  return(
    <>
      <div>
        <div className={styles.cardBody}>
        </div>
      </div>
    </>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.headline}>
        <h1>Заголовок(232)</h1>
      </div>

      <div className={styles.filters}>
        {
          data.map(el => 
            <div className={styles.filterItem}>{el.application}</div>
            )
        }
        {/* <div className={styles.filterItem}>
          1
        </div>

        <div className={styles.filterItem}>
          2
        </div>

        <div className={styles.filterItem}>
          3
        </div> */}
      </div>

      <div className={styles.removeFiltersButton}>
        removeFiltersButton
      </div>

      <div className={styles.cards}>
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
      </div>


    </div>
  )
}
